### ISSUE TITLE
can you find this particular thread in the old forum for me?

### ISSUE THREAD

**Issue by rugabunda** [Sandboxie-Website-Archive/Sandboxie-Website-Archive#1]
Re: DRIVER_VERIFIER_DETECTED_VIOLATION Due to the nature of Sandboxie, MS Driver Verifier will not work with SbieDrv.sys.

in particular:
viewtopic750b750b.html?f=11&amp;t=25636&amp;p=132997#p132997

https://github.com/Sandboxie-Website-Archive/sandboxie-website-archive.github.io/blob/c39bd0ffd7aae669cf01a446b195e758b88f1495/www.sandboxie.com/old-forums/search70b370b3.html

#https://github.com/sandboxie-plus/Sandboxie/issues/31#issue-615499521
#https://github.com/sandboxie-plus/Sandboxie/issues/57#issue-640646460

**Comment by DavidBerdik** [comment]
I believe this is the thread you are looking for: https://sandboxie-website-archive.github.io/www.sandboxie.com/old-forums/viewtopic750b750b.html?f=11&t=25636&p=132997#p132997
