### ISSUE TITLE
i gave you the wrong url, can you point me to this?

### ISSUE THREAD

**Issue by rugabunda** [Sandboxie-Website-Archive/Sandboxie-Website-Archive#2]
@Davidberdik  Damn that was the wrong one, do you have this one? I cant seem to open it on your archive, https://forums.sandboxie.com/phpBB3/viewtopic.php?f=11&t=26535&p=136064#p136064

Thanks david

https://github.com/sandboxie-plus/Sandboxie/issues/57#issue-640646460

**Comment by DavidBerdik** [comment]
Could you tell me what the title of the post was? Unfortunately the archive is not very easy to search even using GitHub's search tools.

**Comment by rugabunda** [comment]
> 
> 
> Could you tell me what the title of the post was? Unfortunately the archive is not very easy to search even using GitHub's search tools.

unfortunately not; BSOD driver verifier, was posted in 2018; its a long and detailed discussion as to why it didn't work;

the only string I can dig up is possibly, "driver verifier does not work with sandboxie"

**Comment by DavidBerdik** [comment]
@rugabunda Is it this one? - https://sandboxie-website-archive.github.io/www.sandboxie.com/old-forums/search70b370b3.html
