### ISSUE TITLE
Website Archive to maintain for xanasoft.com

### ISSUE THREAD

**Issue by isaak654** [Sandboxie-Website-Archive/Sandboxie-Website-Archive#3]
Since the contents of forum.xanasoft.com were destroyed in [2021](https://forum.xanasoft.com/viewtopic.php?f=27&t=8) without any offline backup to restore, I think it would probably be a good idea to perform a HTTrack copy at least once a year and include it in this repository for posterity reasons.

**Comment by DavidBerdik** [comment]
I think it's a good idea to maintain an archive of it too, but given that the forum's scope extends beyond just Sandboxie, I'd probably make it a separate repo instead of including it in this one.

**Comment by isaak654** [comment]
> I'd probably make it a separate repo instead of including it in this one.

In this case, you may want to start from the base domain and capture all existing links.

**Comment by isaak654** [comment]
> I'd probably make it a separate repo instead of including it in this one.

In this case, you may want to start from the base domain `xanasoft.com` and capture all existing links or directly from the base domain `sandboxie-plus.com` (I'm not entirely sure).

**Comment by DavidBerdik** [comment]
It looks to me like the two websites are very tightly-coupled together, so I suspect that doing a scrape of `xanasoft.com` would provide better coverage. Either way, I'd be happy to do it.

**Comment by isaak654** [comment]
I think this might be a good time to plan it as we head into the new year.

**Comment by DavidBerdik** [comment]
Yes, I agree. I'll try to look into this within the next week or two.

**Comment by DavidBerdik** [comment]
I am finally making good on my promise. I've just started running the scraper! I have no idea how long it's going to take, but once it's done, my intention is to create a new repository to host it on.

**Comment by DavidBerdik** [comment]
The Xanasoft Archive repository is now available at https://github.com/Xanasoft-Archive/xanasoft-archive.github.io, so I will close this now.
